<?php 

           /**
            * 秀仙系统 shopxian_release/3.0.0
            * ============================================================================
            * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
            * 网站地址: http://www.shopxian.com；
            * ----------------------------------------------------------------------------
            * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
            * ============================================================================
            * 作者: 张启全 

            * 时间: 2018-03-11 18:25:13
            */
         return [      'Stru'=>[          'id'=>[              'type'=>'int',              'length'=>'10',              'default'=>null,              'unsigned'=>'true',              'not_null'=>'true',              'auto_increment'=>'true',              'comment'=>'单页id',              'zerofill'=>'true',              'auto_increment'=>true,              'label'=>'单页id',              'in_list' => true,              'input_type'=>'hidden',          ],          'title'=>[              'type'=>'varchar',              'length'=>'100',             'comment'=>'标题',              'label'=>'标题',              'in_list' => true,              'is_row_search'=>true,              'is_more_search'=>true,              'input_type'=>'text',          ],          'templet'=>[              'type'=>'varchar',              'length'=>'100',             'default'=>'article_article',              'comment'=>'模版文件',              'label'=>'模版文件',              'in_list' => true,              'input_type'=>'text',          ],          'keywords'=>[              'type'=>'varchar',              'length'=>'255',             'comment'=>'关键词',              'label'=>'关键词',              'in_list' => true,              'input_type'=>'textarea',          ],          'description'=>[             'type'=>'varchar',              'length'=>'255',             'comment'=>'描述',              'label'=>'描述',              'in_list' => true,              'input_type'=>'textarea',          ],          'body'=>[              'type'=>'text',              'length'=>'5000',             'comment'=>'文章内容',              'label'=>'文章内容',              'in_list' => true,              'input_type'=>'baiduUmeditor',          ],          'add_time'=>[              'type'=>'int',              'length'=>'10',             'unsigned'=>'true',              'not_null'=>'true',              'comment'=>'发布时间',              'label'=>'发布时间',              'in_list' => true,              'input_type'=>'hidden',          ],          'rank'=>[              'type'=>'int',              'length'=>'10',             'default'=>'50',              'unsigned'=>'true',              'not_null'=>'true',              'comment'=>'排序值',              'label'=>'排序值(越小越靠前)',              'in_list' => true,              'width'=>'100',              'input_type'=>'number',          ],          'permission'=>[              'type'=>'enum',              'length'=>'2',              'default'=>'1',              'not_null'=>'true',              'comment'=>'阅读权限',              'value'=>array(                  0=>'待审核',                  1=>'开放浏览',              ),              'label'=>'阅读权限',              'in_list' => true,              'width'=>'100',              'input_type'=>'radio',          ],      ],      'Charset'=>'utf8',      'Collate'=>'utf8_unicode_ci',      'Engine'=>'MyISAM',      'Annotation'=>'',      'primary'=>[              'id',      ],  ];  