<?php 

/**
 * 秀仙系统 shopxian_release/3.0.0
 * ============================================================================
 * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.shopxian.com；
 * ----------------------------------------------------------------------------
 * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
 * ============================================================================
 * 作者: 张启全 

 * 时间: 2018-03-15 19:07:22
 */       class PHPExcel_Worksheet_ColumnIterator implements Iterator  {            private $subject;              private $position = 0;              private $startColumn = 0;                private $endColumn = 0;                public function __construct(PHPExcel_Worksheet $subject = null, $startColumn = 'A', $endColumn = null)      {                   $this->subject = $subject;          $this->resetEnd($endColumn);          $this->resetStart($startColumn);      }              public function __destruct()      {          unset($this->subject);      }              public function resetStart($startColumn = 'A')      {          $startColumnIndex = PHPExcel_Cell::columnIndexFromString($startColumn) - 1;          if ($startColumnIndex > PHPExcel_Cell::columnIndexFromString($this->subject->getHighestColumn()) - 1) {              throw new PHPExcel_Exception("Start column ({$startColumn}) is beyond highest column ({$this->subject->getHighestColumn()})");          }            $this->startColumn = $startColumnIndex;          if ($this->endColumn < $this->startColumn) {              $this->endColumn = $this->startColumn;          }          $this->seek($startColumn);            return $this;      }              public function resetEnd($endColumn = null)      {          $endColumn = ($endColumn) ? $endColumn : $this->subject->getHighestColumn();          $this->endColumn = PHPExcel_Cell::columnIndexFromString($endColumn) - 1;            return $this;      }              public function seek($column = 'A')      {          $column = PHPExcel_Cell::columnIndexFromString($column) - 1;          if (($column < $this->startColumn) || ($column > $this->endColumn)) {              throw new PHPExcel_Exception("Column $column is out of range ({$this->startColumn} - {$this->endColumn})");          }          $this->position = $column;            return $this;      }              public function rewind()      {          $this->position = $this->startColumn;      }              public function current()      {          return new PHPExcel_Worksheet_Column($this->subject, PHPExcel_Cell::stringFromColumnIndex($this->position));      }              public function key()      {          return PHPExcel_Cell::stringFromColumnIndex($this->position);      }              public function next()      {          ++$this->position;      }              public function prev()      {          if ($this->position <= $this->startColumn) {              throw new PHPExcel_Exception(                  "Column is already at the beginning of range (" .                  PHPExcel_Cell::stringFromColumnIndex($this->endColumn) . " - " .                  PHPExcel_Cell::stringFromColumnIndex($this->endColumn) . ")"              );          }            --$this->position;      }              public function valid()      {          return $this->position <= $this->endColumn;      }  }  