<?php 

/**
 * 秀仙系统 shopxian_release/3.0.0
 * ============================================================================
 * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.shopxian.com；
 * ----------------------------------------------------------------------------
 * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
 * ============================================================================
 * 作者: 张启全 

 * 时间: 2018-03-15 19:07:22
 */       class PHPExcel_RichText implements PHPExcel_IComparable  {            private $richTextElements;              public function __construct(PHPExcel_Cell $pCell = null)      {                   $this->richTextElements = array();                     if ($pCell !== null) {                           if ($pCell->getValue() != "") {                  $objRun = new PHPExcel_RichText_Run($pCell->getValue());                  $objRun->setFont(clone $pCell->getParent()->getStyle($pCell->getCoordinate())->getFont());                  $this->addText($objRun);              }                             $pCell->setValueExplicit($this, PHPExcel_Cell_DataType::TYPE_STRING);          }      }              public function addText(PHPExcel_RichText_ITextElement $pText = null)      {          $this->richTextElements[] = $pText;          return $this;      }              public function createText($pText = '')      {          $objText = new PHPExcel_RichText_TextElement($pText);          $this->addText($objText);          return $objText;      }              public function createTextRun($pText = '')      {          $objText = new PHPExcel_RichText_Run($pText);          $this->addText($objText);          return $objText;      }              public function getPlainText()      {                   $returnValue = '';                     foreach ($this->richTextElements as $text) {              $returnValue .= $text->getText();          }                     return $returnValue;      }              public function __toString()      {          return $this->getPlainText();      }              public function getRichTextElements()      {          return $this->richTextElements;      }              public function setRichTextElements($pElements = null)      {          if (is_array($pElements)) {              $this->richTextElements = $pElements;          } else {              throw new PHPExcel_Exception("Invalid PHPExcel_RichText_ITextElement[] array passed.");          }          return $this;      }              public function getHashCode()      {          $hashElements = '';          foreach ($this->richTextElements as $element) {              $hashElements .= $element->getHashCode();          }            return md5(              $hashElements .              __CLASS__          );      }              public function __clone()      {          $vars = get_object_vars($this);          foreach ($vars as $key => $value) {              if (is_object($value)) {                  $this->$key = clone $value;              } else {                  $this->$key = $value;              }          }      }  }  