<?php 

/**
 * 秀仙系统 shopxian_release/3.0.0
 * ============================================================================
 * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.shopxian.com；
 * ----------------------------------------------------------------------------
 * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
 * ============================================================================
 * 作者: 张启全 

 * 时间: 2018-03-15 19:07:22
 */   namespace lib\base;      class SiteController extends BaseController{      protected $member_id='';      protected $member_name='';          function __construct($login = true) {          $this->member_id= session("member_id");          $this->member_name= session("member_name");          parent::__construct(false);      }      public function __404(){                   return $this->fetch(shopXianEnv('extend_path').'view/base/'.$this->site_type.'/404.html');      }      public function template($app,$df_style,$template, $vars = [], $config = [],$static=false){          $dir='template/'.$app.'/'.$df_style.'/'.$this->site_type.'/';          $tpl=dirname($_SERVER['SCRIPT_FILENAME']).DIRECTORY_SEPARATOR.$dir.$template.'.html';          if(!file_exists($tpl)){              $dir='template/'.$app.'/'.$df_style.'/site/';              $tpl=dirname($_SERVER['SCRIPT_FILENAME']).DIRECTORY_SEPARATOR.$dir.$template.'.html';          }          $css_dir=$dir.'css';          $img_dir=$dir.'img';          $js_dir=$dir.'js';          $domain=request()->domain().explode('index.php', $_SERVER['SCRIPT_NAME'])[0];          $this->assign("css_dir", $domain.$css_dir);          $this->assign("img_dir", $domain.$img_dir);          $this->assign("js_dir", $domain.$js_dir);          $fetch=$this->fetch($tpl, $vars, $config);          if($static&&isset($_SERVER['PATH_INFO'])&&$_SERVER['PATH_INFO']){              if($_SERVER['PATH_INFO']=='/')$_SERVER['PATH_INFO']='/index.'. config('url_html_suffix');              $static_file= $_SERVER['PATH_INFO'];              $file_dir= dirname($static_file);              mkdirs ($file_dir);              $static_file= dirname($_SERVER['SCRIPT_FILENAME']).$_SERVER['PATH_INFO'];              file_put_contents($static_file, $fetch);          }else if($static){              file_put_contents('index.html', $fetch);          }                  return $fetch;      }              public function showStaticTpl(string $tpl_name = '', array $data = [],string $cache_path='') {          $cache_path_past=$cache_path;          $cache_path=dirname($_SERVER['SCRIPT_FILENAME']).DIRECTORY_SEPARATOR.$cache_path;          $html=parent::showTpl($tpl_name, $data);                   mkdirs($cache_path_past);          file_put_contents($cache_path,$html);          return $html;      }  }  