<?php 

/**
 * 秀仙系统 shopxian_release/3.0.0
 * ============================================================================
 * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.shopxian.com；
 * ----------------------------------------------------------------------------
 * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
 * ============================================================================
 * 作者: 张启全 

 * 时间: 2018-03-15 19:07:22
 */       namespace lib\base;  class Yihu {        public  function send($uname,$pwd,$mb,$scode,$neirong){          $target = "http:         $mobile = $mb;          $send_code = $scode;            $mobile_code = $scode;         if(empty($mobile)){                  return '手机号码不能为空';          }                    if(($_SESSION['send_code_time']+30)>=time()){                           return '操作过于频繁,请稍后再试!2次发送验证码的时间不能小于30秒!请30秒重新获取';          }            $post_data = "account={$uname}&password={$pwd}&mobile=".$mobile."&content=".rawurlencode($neirong);                   $gets = $this->xml_to_array($this->Post($post_data, $target));          if($gets['SubmitResult']['code']==2){          }          $_SESSION['mobile'] = $mobile;          $_SESSION['mobile_code'] = $mobile_code;          $_SESSION['send_code_time']=  time();          return $gets['SubmitResult']['msg'];      }      protected function Post($curlPost,$url){                      $curl = curl_init();                      curl_setopt($curl, CURLOPT_URL, $url);                      curl_setopt($curl, CURLOPT_HEADER, false);                      curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);                      curl_setopt($curl, CURLOPT_NOBODY, true);                      curl_setopt($curl, CURLOPT_POST, true);                      curl_setopt($curl, CURLOPT_POSTFIELDS, $curlPost);                      $return_str = curl_exec($curl);                      curl_close($curl);                      return $return_str;      }      protected function xml_to_array($xml){              $reg = "/<(\w+)[^>]*>([\\x00-\\xFF]*)<\\/\\1>/";              if(preg_match_all($reg, $xml, $matches)){                      $count = count($matches[0]);                      for($i = 0; $i < $count; $i++){                      $subxml= $matches[2][$i];                      $key = $matches[1][$i];                              if(preg_match( $reg, $subxml )){                                      $arr[$key] = self::xml_to_array( $subxml );                              }else{                                      $arr[$key] = $subxml;                              }                      }              }              return $arr;      }      protected function random($length = 6 , $numeric = 0) {              PHP_VERSION < '4.2.0' && mt_srand((double)microtime() * 1000000);              if($numeric) {                      $hash = sprintf('%0'.$length.'d', mt_rand(0, pow(10, $length) - 1));              } else {                      $hash = '';                      $chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789abcdefghjkmnpqrstuvwxyz';                      $max = strlen($chars) - 1;                      for($i = 0; $i < $length; $i++) {                              $hash .= $chars[mt_rand(0, $max)];                      }              }              return $hash;      }  }  