<?php 

/**
 * 秀仙系统 shopxian_release/3.0.0
 * ============================================================================
 * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.shopxian.com；
 * ----------------------------------------------------------------------------
 * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
 * ============================================================================
 * 作者: 张启全 

 * 时间: 2018-03-17 23:28:45
 */   namespace lib\base;      class Zip {      private $zip;     private $file;     private $farr=array();     public function __construct($file) {          $this->zip = new \ZipArchive;          $this->file=$file;      }            private function mkdir(){          if(!file_exists($this->file)){              $fpatharr=explode('/', $this->file);              $count=count($fpatharr);              $dir='';              for($i=0;$i<$count-1;$i++){                  $dir=$dir.$fpatharr[$i].'/';                  if(!file_exists($dir)){                      mkdir($dir);                  }              }          }      }              public function addfile($file){          $this->mkdir();         $ret =$this->zip->open($this->file,\ZipArchive::OVERWRITE);          if ($ret==FALSE) {              printf('压缩文件失败', $ret);          }  else {              $this->zip->addFile($file,pathinfo($file)['basename']);              return true;          }      }            public function adddir($dir){          $this->hookDir($dir);          $this->mkdir();         $ret =$this->zip->open($this->file, \ZipArchive::OVERWRITE);          if ($ret !== TRUE) {              printf('压缩目录失败', $ret);          }else{                          foreach ($this->farr as $k => $v) {                  $directory = realpath($v);                  $options = array('add_path' => $v, 'remove_path' => $directory);                 $this->zip->addPattern('*.*', $directory, $options);                  }              }              return true;      }            public function extract($Savepath){          $this->mkdir();          $ret =$this->zip->open($this->file);          if ($ret !== TRUE) {              printf('打开压缩文件失败', $ret);          }  else {              $this->zip->extractTo($Savepath);              return true;          }      }              public function close(){          $this->zip->close();      }            private function hookDir($dir){          $scdir=scandir($dir);          foreach ($scdir as $k => $v) {              if(is_dir($dir.$v)&&  file_exists($dir.$v)&&$v!='.'&&$v!='..'){                  $this->farr[]=$dir.$v.'/';                  $this->hookDir($dir.$v.'/');              }          }      }  }                   