<?php 
 
return [ 
    [ 
        "id"=>"system", 
        "name"=>"系统设置", 
        "app"=>"system", 
        "controller"=>"system", 
        "method"=>"index", 
        "rank"=>"500", 
        "display"=>true, 
        "arg"=>"", 
        "menu"=>[ 
            [ 
                "name"=>"应用中心", 
                "app"=>"base", 
                "controller"=>"AdminApp", 
                "method"=>"index", 
                "rank"=>"20", 
                "display"=>true, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"应用安装", 
                "app"=>"base", 
                "controller"=>"AdminApp", 
                "method"=>"install", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"应用卸载", 
                "app"=>"base", 
                "controller"=>"AdminApp", 
                "method"=>"unInstall", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"应用维护", 
                "app"=>"base", 
                "controller"=>"AdminApp", 
                "method"=>"maintain", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"应用菜单维护", 
                "app"=>"base", 
                "controller"=>"AdminApp", 
                "method"=>"dbUpdate", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"应用表维护", 
                "app"=>"base", 
                "controller"=>"AdminApp", 
                "method"=>"menuUpdate", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"系统日志", 
                "app"=>"base", 
                "controller"=>"AdminAppLog", 
                "method"=>"index", 
                "rank"=>"20", 
                "display"=>true, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"系统日志批量删除", 
                "app"=>"base", 
                "controller"=>"AdminAppLog", 
                "method"=>"finderDel", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"系统日志清空", 
                "app"=>"base", 
                "controller"=>"AdminAppLog", 
                "method"=>"clearAll", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
        ]  
    ] 
]; 
 
