<?php 
return [
	'type'=>'mysql',
	'dsn'=>'',
	'hostname'=>'127.0.0.1',
	'database'=>'shopxian111',
	'username'=>'root',
	'password'=>'',
	'hostport'=>'3306',
	'params'=>[],
	'charset'=>'utf8',
	'prefix'=>'zs_',
	'debug'=>'1',
	'deploy'=>'0',
	'rw_separate'=>'',
	'master_num'=>'1',
	'slave_no'=>'',
	'fields_strict'=>'1',
	'resultset_type'=>'array',
	'auto_timestamp'=>'',
	'datetime_format'=>'Y-m-d H:i:s',
	'sql_explain'=>'',
	'query'=>'\think\db\Query',
	'break_reconnect'=>'1',
];