<?php 

/**
 * 秀仙系统 shopxian_release/3.0.0
 * ============================================================================
 * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.shopxian.com；
 * ----------------------------------------------------------------------------
 * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
 * ============================================================================
 * 作者: 张启全 

 * 时间: 2018-03-15 19:07:21
 */   return [      'Stru'=>[          'id'=>[              'type'=>'int',              'length'=>'11',              'default'=>null,              'unsigned'=>'true',              'not_null'=>'true',              'comment'=>'id',              'auto_increment'=>true,              'label'=>'id',              'in_list' => true,              'input_type'=>'hidden',          ],          'app_name'=>[              'type'=>'varchar',              'length'=>'60',             'comment'=>'应用名称',              'label'=>'应用名称',              'width'=>'200',              'in_list' => true,              'default_in_list' => true,              'search_allow' => true,              'not_null'=>'true',               'input_type'=>'readonly',          ],          'table_name'=>[              'type'=>'varchar',              'length'=>'100',             'comment'=>'表名',              'label'=>'表名',              'in_list' => true,              'not_null'=>'true',               'input_type'=>'readonly',          ],          'file_path'=>[              'type'=>'varchar',              'length'=>'255',             'comment'=>'导入源文件',              'label'=>'导入源文件',              'in_list' => true,              'not_null'=>'true',               'input_type'=>'file',          ],          'add_time'=>[              'type'=>'int',              'length'=>'11',             'comment'=>'添加时间',              'label'=>'添加时间',              'in_list' => true,              'not_null'=>'true',               'input_type'=>'hidden',          ],          'last_time'=>[              'type'=>'int',              'length'=>'11',             'comment'=>'最后更新时间',              'label'=>'最后更新时间',              'in_list' => true,              'input_type'=>'hidden',          ],          'states'=>[              'type'=>'enum',              'length'=>'5',             'default'=>'0',              'not_null'=>'true',              'comment'=>'状态',              'width'=>'120',              'value'=>array(                  -1=>'导入失败',                  0=>'待导入',                  1=>'导入中',                  2=>'导入完成',              ),              'label'=>'状态',              'in_list' => true,              'default_in_list' => true,              'search_allow' => true,              'input_type'=>'hidden',          ],          'states_msg'=>[              'type'=>'varchar',              'length'=>'255',             'comment'=>'状态说明',              'label'=>'状态说明',              'in_list' => true,              'input_type'=>'hidden',          ],          'msg'=>[              'type'=>'varchar',              'length'=>'255',             'comment'=>'备注信息',              'label'=>'备注信息',              'in_list' => true,              'input_type'=>'hidden',          ],      ],      'Charset'=>'utf8',      'Collate'=>'utf8_unicode_ci',      'Engine'=>'InnoDB',      'Annotation'=>'',      'primary'=>[              'id',      ],  ];  