<?php 

           /**
            * 秀仙系统 shopxian_release/3.0.0
            * ============================================================================
            * * 版权所有 2017-2018 上海秀仙网络科技有限公司，并保留所有权利。
            * 网站地址: http://www.shopxian.com；
            * ----------------------------------------------------------------------------
            * 本软件只能免费使用  不允许对程序代码以任何形式任何目的再发布或者出售。
            * ============================================================================
            * 作者: 张启全 

            * 时间: 2018-03-11 16:08:51
            */
           return [      'Stru'=>[          'id'=>[              'type'=>'bigint',              'length'=>'20',              'default'=>null,              'unsigned'=>'true',              'not_null'=>'true',              'comment'=>'队列id',              'auto_increment'=>true,              'label'=>'队列id',              'in_list' => true,              'input_type'=>'text',          ],          'queue_name' => array (              'type'=>'varchar',              'length'=>'60',             'comment'=>'队列标识',              'label'=>'队列标识',              'in_list' => true,              'is_row_search'=>true,              'is_more_search'=>true,              'input_type'=>'text',          ),          'worker'=>array(              'type'=>'varchar',              'length'=>'255',             'comment'=>'执行任务类',              'label'=>'执行任务类',              'in_list' => true,              'is_row_search'=>true,              'is_more_search'=>true,              'input_type'=>'text',          ),          'method'=>array(              'type'=>'varchar',              'length'=>'255',             'comment'=>'执行方法',              'label'=>'执行方法',              'in_list' => true,              'is_row_search'=>true,              'is_more_search'=>true,              'input_type'=>'text',          ),          'params'=>array(              'type'=>'text',              'length'=>'5000',             'comment'=>'任务参数',              'label'=>'任务参数',              'in_list' => true,              'is_row_search'=>true,              'is_more_search'=>true,              'input_type'=>'text',          ),          'create_time' => array (              'type'=>'int',              'length'=>'10',             'default'=>'0',              'comment'=>'创建时间',              'label'=>'创建时间',              'in_list' => true,          ),          'last_cosume_time' => array(              'type'=>'int',              'length'=>'10',             'default'=>'0',              'comment'=>'任务开始执行时间',              'label'=>'任务开始执行时间',              'in_list' => true,          ),          'msg'=>array(              'type'=>'varchar',              'length'=>'255',             'comment'=>'执行错误信息',              'label'=>'执行错误信息',              'in_list' => true,              'input_type'=>'text',          ),      ],      'Charset'=>'utf8',      'Collate'=>'utf8_unicode_ci',      'Engine'=>'InnoDB',      'Annotation'=>'',      'primary'=>[              'id',      ],  ];  