<?php 
 
return [ 
    [ 
        "id"=>"system", 
        "name"=>"系统设置", 
        "app"=>"system", 
        "controller"=>"system", 
        "method"=>"index", 
        "rank"=>"500", 
        "display"=>true, 
        "arg"=>"", 
        "menu"=>[ 
            [ 
                "name"=>"缓存管理", 
                "app"=>"system", 
                "controller"=>"AdminCache", 
                "method"=>"cache", 
                "rank"=>"1", 
                "display"=>true, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"缓存清理操作", 
                "app"=>"system", 
                "controller"=>"AdminCache", 
                "method"=>"cacheDataDel", 
                "rank"=>"1", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"日志清理操作", 
                "app"=>"system", 
                "controller"=>"AdminCache", 
                "method"=>"cacheLogDel", 
                "rank"=>"1", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"模版清理操作", 
                "app"=>"system", 
                "controller"=>"AdminCache", 
                "method"=>"cacheDataDel", 
                "rank"=>"1", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"静态清理操作", 
                "app"=>"system", 
                "controller"=>"AdminCache", 
                "method"=>"cacheStaticDel", 
                "rank"=>"1", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"全局参数", 
                "app"=>"base", 
                "controller"=>"AdminAppConfig", 
                "method"=>"get", 
                "rank"=>"20", 
                "display"=>true, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"全局参数编辑", 
                "app"=>"base", 
                "controller"=>"AdminAppConfig", 
                "method"=>"finderAdd", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ], 
            [ 
                "name"=>"全局参数保存", 
                "app"=>"base", 
                "controller"=>"AdminAppConfig", 
                "method"=>"autoToAdd", 
                "rank"=>"20", 
                "display"=>false, 
                "arg"=>"" 
            ] 
        ]  
    ] 
]; 
 
